name: crowd_dashboard
publish_to: "none"
version: 0.0.1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  amplify_flutter: ^2.6.1
  amplify_api: ^2.6.1
  # Optional – for buttons/icons/UI polish
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  amplify_secure_storage_dart: ^0.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
